# Generated by Django 3.0 on 2019-12-13 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=10)),
                ('lastLogin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=20)),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testerSearch.Tester')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ManyToManyField(to='testerSearch.Device')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testerSearch.Tester')),
            ],
        ),
    ]
