# Generated by Django 3.0 on 2019-12-15 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testerSearch', '0002_auto_20191214_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='device',
        ),
        migrations.AddField(
            model_name='bug',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testerSearch.Device'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='tester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testerSearch.Tester'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='tester',
        ),
        migrations.AddField(
            model_name='device',
            name='tester',
            field=models.ManyToManyField(to='testerSearch.Tester'),
        ),
    ]
